aws-solutions/amazon-marketing-cloud-uploader-from-aws

source/amc_uploader/amc_uploader.py, source/glue/amc_transformations.py
=> Fix logging statement

.github/workflows/selenium-workflow.yml, .gitignore, source/tests/e2e/conftest.py, source/tests/e2e/requirements.txt, source/tests/e2e/run_e2e.sh, source/tests/e2e/test_app.py
=> add selenium tests to validate front-end

deployment/amazon-marketing-cloud-uploader-from-aws.yaml
=> remove unused lambda layer

source/website/vue.config.js
=> enable SRI integrity checks

.github/workflows/pr-workflow.yml, deployment/build-s3-dist.sh
*Issue #, if available:* #20
*Description of changes:* Explicitly use python 3.9 in deploy script.
=>  Resolve "Chalice fails with Python 3.10"

.github/workflows/pr-workflow.yml, .github/workflows/selenium-workflow.yml
Closes #31 
The selenium-workflow is broken due to invalid yaml, blank user_pool_id, and maybe more. Close this issue when the selenium-workflow works.
=> fix selenium-workflow

.viperlightignore, CHANGELOG.md, deployment/amazon-marketing-cloud-uploader-from-aws.yaml, deployment/glue.yaml, source/amc_uploader/requirements.txt, source/api/external_resources.json, source/helper/webapp-manifest.json
=> Remove us east 1 dependency

.github/workflows/pr-workflow.yml, deployment/build-s3-dist.sh, source/amc_uploader/requirements.txt, source/api/app.py, source/api/tests/requirements-test.txt, source/api/tests/test_api_integration.py
Reverts aws-solutions/amazon-marketing-cloud-uploader-from-aws#53
Revert the revert.
After talking with Immanuel, I realized that we need to keep the integ test. Rather than revert it, I need to update it in the PR where it failed.
=> Revert "Revert "update pr workflow test api integ test""

deployment/amazon-marketing-cloud-uploader-from-aws.yaml
Closes #57 
increase lambda timeout to 15 min
=> increase helper function lambda timeout

source/glue/amc_transformations.py
=> make timestamp_column an optional arg to Glue

.github/workflows/pr-workflow.yml, .viperlightignore, CHANGELOG.md, deployment/build-s3-dist.sh, deployment/glue.yaml, source/api/tests/test_api_integration.py, source/glue/amc_transformations.py, source/glue/normalizers/email_normalizer.py, source/tests/amc_transformation/test_amc_transformation.py, source/tests/amc_uploader/test_amc_uploader.py
#13 
- normalize invalid email to empty string
- add unit test
- add unit test to github workflow
=> invalid email addresses should normalize to empty string

.viperlightignore, deployment/amazon-marketing-cloud-uploader-from-aws.yaml, deployment/build-s3-dist.sh, deployment/lambda_layer_factory/Dockerfile, deployment/lambda_layer_factory/build-lambda-layer.sh, deployment/lambda_layer_factory/docker-entrypoint.sh, deployment/lambda_layer_factory/requirements.txt, source/amc_uploader/requirements.txt, source/api/external_resources.json, source/api/requirements.txt
Closes #65 
The python package for aws-xray-sdk increases the size of Lambda packages beyond the limits that are allowed by the source code editor in the Lambda console. In order to fix this, I've packaged aws-xray-sdk into a custom lambda layer, so that the code editor can be used.
It is particularly important to be able to use the Lambda code editor in order to quickly iterate on changes to the API Handler.
=> use custom lambda layer for aws-xray-sdk

.github/workflows/pr-workflow.yml, .github/workflows/selenium-workflow.yml, deployment/build-s3-dist.sh, deployment/lambda_layer_factory/build-lambda-layer.sh
=> migrate from python3.9 to python 3.10

.gitignore, source/amc_uploader/lib/sigv4.py, source/api/chalicelib/sigv4.py
#99 
Resolve SonarQube errors on duplicated Lines
=> SonarQube fix duplication errors

CHANGELOG.md, source/tests/e2e/conftest.py, source/tests/e2e/run_e2e.sh, source/tests/e2e/test_app.py, source/website/src/views/Step3.vue
Reverts aws-solutions/amazon-marketing-cloud-uploader-from-aws#69
=> Revert "Add feature to export and import schemas"

deployment/glue.yaml, source/glue/amc_transformations.py
#131 
Minor improvements to country_code treatment for Glue job.
=> add missing country_code argument

source/website/src/views/Step6.vue
Closes #147
Description of changes:
Implement sort-compare function to sort using datetime logic.
=> fix incorrect sort on the glue job table

source/.coveragerc
=> Set Coverage Fail Under to 82%

source/api/tests/test_api_integration.py, source/glue/amc_transformations.py
- syntax error fix
- update integration test to reflect arguments passed in prod
- add new argument validation check
=> fix argument handling for dimension datasets

source/api/tests/test_api_integration.py, source/glue/amc_transformations.py
=> Update 2.0 with development

source/anonymous_data_logger/anonymous_lib/cfnresponse.py
Closes #161 
Add timeout to call to python `requests`.
=> Request without timeout

CHANGELOG.md, README.md, source/amc_uploader/lib/sigv4.py, source/api/chalicelib/sigv4.py, source/api/tests/test_api_integration.py, source/api/tests/test_api_unit_test.py, source/tests/amc_uploader/test_amc_uploader.py
=> Handle HTTP 504 "Endpoint request timed out" error in AmcUploader lambda

source/amc_uploader/lib/sigv4.py, source/api/chalicelib/sigv4.py, source/api/tests/requirements-test.txt, source/api/tests/test_api_integration.py
=> Wait for AMC upload to complete before cleanup

source/anonymous_data_logger/anonymous_lib/cfnresponse.py, source/api/app.py, source/api/tests/test_api_integration.py, source/glue/library/read_write.py, source/website/src/views/Settings.vue
N/A
- Refactored `get_data_columns` endpoint to more functions to reduce cognitive complexity and resolve SonarQube code smell
- Other formatting changes done by pre-commit linter
=> Fix - reduce SonarQube cognitive complexity and formatting

source/tests/amc_transformation/test_amc_transformation.py
=> update integ test for changes to endpoint encoding

source/api/app.py
=> Decrease log verbosity

README.md, deployment/build-s3-dist.sh
Closes #15 
Closes #116 
Update deploy instructions for v2.0.0
=> Update deploy instructions for v2.0.0

source/tests/README.md
=> Update Test README.md

deployment/build-s3-dist.sh, sonar-project.properties
=> SonarQube picking up dist folder

source/glue/library/read_write.py
#195 
Add the dataset period into glue job usage metrics.
=> Record dataset period

source/api/app.py, source/tests/unit_test/test_api.py, source/website/src/views/Step4.vue
Closes #197
Add user_id and user_type columns alongside liveramp column.
=> add required user columns alongside liveramp

CHANGELOG.md, deployment/amazon-marketing-cloud-uploader-from-aws.yaml, deployment/web.yaml
Close #228 
Set s3 object ownership in order to maintain compatibility with s3 access logging.
=> S3 object ownership

.gitignore, .viperlightignore, CHANGELOG.md, README.md, deployment/amazon-marketing-cloud-uploader-from-aws.yaml, deployment/glue.yaml, solution-manifest.yaml, sonar-project.properties, source/anonymous_data_logger/requirements.txt, source/api/app.py, source/glue/amc_transformations.py, source/glue/library/read_write.py, source/requirements-dev.txt, source/tests/requirements-test.txt, source/tests/unit_test/amc_transformation/test_amc_transformation.py, source/tests/unit_test/test_api.py, source/website/package-lock.json, source/website/package.json, source/website/src/components/VoerroTagsInput.css, source/website/src/components/VoerroTagsInput.vue, source/website/src/views/Settings.vue, source/website/src/views/Step2.vue, source/website/src/views/Step3.vue, source/website/src/views/Step4.vue, source/website/src/views/Step5.vue, source/website/src/views/Step6.vue
Copy release/v2.2.0 to the main branch.
=> add v2.2.0 release candidate to github

CHANGELOG.md, README.md, solution-manifest.yaml, source/website/package-lock.json, source/website/package.json
Copy release/v2.3.1 to the main branch.
=> add v2.3.1 release candidate to github

README.md, deployment/amazon-marketing-cloud-uploader-from-aws.yaml, source/anonymous_data_logger/requirements.txt, source/share/tasks.py, source/website/package-lock.json, source/website/package.json
n/a
Copy release/v3.0.1 to the main branch.
=> add v3.0.1 release candidate to github

CHANGELOG.md, NOTICE.txt, README.md, deployment/amazon-marketing-cloud-uploader-from-aws.yaml, deployment/auth.yaml, deployment/glue.yaml, deployment/lambda_layer_factory/Dockerfile, deployment/web.yaml, solution-manifest.yaml, source/amc_uploader/amc_uploader.py, source/api/external_resources.json, source/glue/amc_transformations.py, source/glue/library/read_write.py, source/share/tasks.py, source/tests/unit_test/amc_uploader/test_amc_uploader.py, source/tests/unit_test/test_api.py, source/website/package-lock.json, source/website/package.json, source/website/src/views/Settings.vue, source/website/src/views/Step4.vue, source/website/src/views/Step5.vue, source/website/src/views/Step6.vue
n/a
Copy release/v3.0.2 to the main branch.
=> add v3.0.2 release candidate to github

CHANGELOG.md, NOTICE.txt, README.md, solution-manifest.yaml, source/amc_uploader/setup.py, source/cognito_hosted_ui_resource/cognito_hosted_ui_resource.py, source/share/tasks.py, source/website/package-lock.json, source/website/package.json
N/A
Copy release/v3.0.5 to the main branch.
=> add v3.0.5 release candidate to github

CHANGELOG.md, solution-manifest.yaml, source/share/tasks.py, source/website/package-lock.json, source/website/package.json
=> Changes for v3.0.6

CHANGELOG.md, solution-manifest.yaml, source/requirements-dev.txt, source/share/tasks.py, source/tests/requirements-test.txt, source/website/package-lock.json, source/website/package.json
Dependency version change for awswrangler.
=> Changes for v3.0.7

CHANGELOG.md, solution-manifest.yaml, source/share/tasks.py, source/website/package-lock.json, source/website/package.json
=> Changes for v3.0.10

CHANGELOG.md, NOTICE.txt, solution-manifest.yaml, source/share/tasks.py, source/website/package-lock.json, source/website/package.json
=> Changes for v3.0.11
